data_local: /data/gigapile/mds_shards
data_remote:  # If blank, files must be present in data_local

pretrain_data_local: pretrain_data_folder  # unused when eval_loader is removed
pretrain_data_remote:  # If blank, files must be present in pretrain_data_local

max_seq_len: 8192
tokenizer_name: answerdotai/ModernBERT-large
mlm_probability: 0.3  # 30% masking for optimal FlexBERT performance
count_padding_tokens: false

# Run identifiers
run_name: modernbert-large-learning-rate-decay
context_extension_run_name: modernbert-large-context-extension

# Model
model:
  name: flex_bert
  pretrained_model_name: bert-base-uncased
  tokenizer_name: ${tokenizer_name}
  disable_train_metrics: true
  model_config:
    vocab_size: 50368
    init_method: full_megatron
    num_hidden_layers: 28
    hidden_size: 1024
    intermediate_size: 2624
    num_attention_heads: 16
    attention_layer: rope
    attention_probs_dropout_prob: 0.0
    attn_out_bias: false
    attn_out_dropout_prob: 0.1
    attn_qkv_bias: false
    bert_layer: prenorm
    embed_dropout_prob: 0.0
    embed_norm: true
    final_norm: true
    skip_first_prenorm: true
    embedding_layer: sans_pos
    loss_function: fa_cross_entropy
    loss_kwargs:
      reduction: mean
    mlp_dropout_prob: 0.0
    mlp_in_bias: false
    mlp_layer: glu
    mlp_out_bias: false
    normalization: layernorm
    norm_kwargs:
      eps: 1e-5
      bias: false
    hidden_act: gelu
    head_pred_act: gelu
    activation_function: gelu
    padding: unpadded
    rotary_emb_dim: null
    rotary_emb_base: 160000.0
    rotary_emb_scale_base: null
    rotary_emb_interleaved: false
    local_attn_rotary_emb_base: 10000.0
    local_attn_rotary_emb_dim: null
    allow_embedding_resizing: true
    sliding_window: 128
    global_attn_every_n_layers: 3
    unpad_embeddings: true
    compile_model: true
    masked_prediction: true

# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split:
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: true
    mlm_probability: ${mlm_probability}
    streaming: false
    shuffle_seed: 2998
  drop_last: true
  num_workers: 6
  sequence_packing: true

# (eval_loader removed to disable validation)

# Optimization & schedule
scheduler:
  name: one_minus_sqrt
  alpha_f: 0.001
  t_decay: ${max_duration}
  t_max: ${max_duration}

optimizer:
  name: decoupled_stableadamw
  lr: 5e-5
  betas:
    - 0.9
    - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-6
  filter_bias_norm_wd: true
  log_grad_norm: true

# Train until you’ve consumed ~1.1985 trillion tokens
max_duration: 1198510347252tok
eval_interval: 0            # disable all validation
global_train_batch_size: 12
global_eval_batch_size: 12   # unused when eval is disabled

# System / hardware
seed: 314
device_eval_microbatch_size: 2
device_train_microbatch_size: 2  # per-GPU microbatch on your 6×40 GB A100s
precision: amp_bf16

# Logging & callbacks
progress_bar: false
log_to_console: true
console_log_interval: 10ba #500ba

callbacks:
  speed_monitor:
    window_size: 50
  lr_monitor: {}
  scheduled_gc: {}
  log_grad_norm:
    batch_log_interval: 10
  packing_efficiency:
    log_interval: 10

# Checkpointing
save_interval: 1000ba
save_num_checkpoints_to_keep: -1
save_folder: checkpoints/{run_name}

# Load the remote “answerdotai/ModernBERT-large” model and reset optimizer/scheduler state
load_path: /data/models/ModernBERT-large/modernbert_large_hf_ckpt.pt
autoresume: false
reset_time: true
restart_override: true
