# Data paths
data_local: /scratch/project_462000936/data/packed_full
data_remote: # If blank, files must be present in data_local

# Sequence & tokenizer
max_seq_len: 8192
tokenizer_name: answerdotai/ModernBERT-large
mlm_probability: 0.3
count_padding_tokens: false

# Run Name
run_name: modernbert-large-pretrain

# Model
model:
  name: flex_bert
  pretrained_model_name: bert-base-uncased # has to be set to bert-base-uncased legacy reasons
  tokenizer_name: ${tokenizer_name}
  disable_train_metrics: true # save some time by not computing metrics on the training set
  model_config:
    vocab_size: 50368
    init_method: full_megatron
    num_hidden_layers: 28
    hidden_size: 1024
    intermediate_size: 2624
    num_attention_heads: 16 # to have head size of 64
    attention_layer: rope
    attention_probs_dropout_prob: 0.0
    attn_out_bias: false
    attn_out_dropout_prob: 0.1
    attn_qkv_bias: false
    bert_layer: prenorm
    embed_dropout_prob: 0.0
    embed_norm: true
    final_norm: true
    skip_first_prenorm: true
    embedding_layer: sans_pos
    loss_function: fa_cross_entropy
    loss_kwargs:
      reduction: mean
    mlp_dropout_prob: 0.0
    mlp_in_bias: false
    mlp_layer: glu
    mlp_out_bias: false
    normalization: layernorm
    norm_kwargs:
      eps: 1e-5
      bias: false
    hidden_act: gelu
    head_pred_act: gelu
    activation_function: gelu # better safe than sorry
    padding: unpadded
    rotary_emb_dim: null
    rotary_emb_base: 160000.0
    rotary_emb_scale_base: null
    rotary_emb_interleaved: false
    local_attn_rotary_emb_base: 10000.0
    local_attn_rotary_emb_dim: null
    allow_embedding_resizing: true
    sliding_window: 128
    global_attn_every_n_layers: 3
    unpad_embeddings: true
    compile_model: true
    masked_prediction: true

# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: true
    mlm_probability: ${mlm_probability}
    streaming: true
  drop_last: true
  num_workers: 24
  sequence_packing: false
  persistent_workers: true
  pin_memory: true

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 11_985_103_472tok # 1% of total ds
  t_max: ${max_duration}
  alpha_f: 0.001

optimizer:
  name: decoupled_stableadamw
  lr: 2e-4
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-5
  filter_bias_norm_wd: true
  log_grad_norm: true

# Training duration & batch sizes
max_duration: 1_198_510_347_252tok
eval_interval: 0
global_train_batch_size: 192
global_eval_batch_size: 192

# System settings
seed: 420
device_eval_batch_size: 3
device_train_microbatch_size: 3
precision: amp_bf16

# Logging & callbacks
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 25
  lr_monitor: {}
  scheduled_gc: {}
  log_grad_norm:
    batch_log_interval: 25
  packing_efficiency:
    log_interval: 25

# Checkpointing
save_interval: 3750ba
save_num_checkpoints_to_keep: 3
save_folder: checkpoints/{run_name}
load_path: modernbert_large_hf_ckpt.pt
autoresume: true

#loggers:
#  wandb:
#    project: modernbert-large-pretrain
#    entity: nlu-group
#    init_kwargs: {"mode" : "offline"}
